spring.profiles.active=dev


spring.application.name=clientes-backEnd
server.port=8080
org.gradle.daemon=false
# DataSource settings
spring.datasource.url=jdbc:mariadb://localhost:13001/clientesDBB?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=irvin2002822
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.format_sql=true

# Logging settings
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Habilitar CORS globalmente
#spring.web.cors.allowed-origins=http://localhost:4200
#spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
#spring.web.cors.allowed-headers=Authorization,Content-Type
#spring.web.cors.allow-credentials=true
